### PR TITLE
Code Refactor + minor fixes

### PR DESCRIPTION
**Pull request by CodeByAidan**
plz add renovate bot so u can keep up with ur requirements (i updated the requirements with version numbers)

I also made detailed explanation on each of my commits so take a look :)

### CODE REVIEW

**Review by CodeByAidan — COMMENTED** [review]
thanks black

**Comment by SawshaDev** [comment]
Hey, mind if you give me your discord so i can discuss these changes more thoroughly with you through there?

my disc is Sawsha#0598, i would love to talk to you more about this changes!

**Comment by CodeByAidan** [comment]
plz pzlplz pzlplz plz plzlplpzlp zpz polz pllpz pl

**Comment by SawshaDev** [comment]
LGTM, thanks for all of this

**Pull request merged**
